service: otel-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  tracing:
    lambda: true
  architecture: arm64
custom:
  pythonRequirements:
    slim: true
    dockerizePip: true
    dockerRunCmdExtraArgs: [ '--platform', 'linux/arm64/v8' ]
    dockerImage: public.ecr.aws/sam/build-python3.9:latest-arm64
plugins:
  - serverless-python-requirements
	
package:
  patterns:
    - '!node_modules/**'
    - '!infra/terraform/**'
 
functions:
  hello:
    module: .
    handler: handler.get_repos
    environment:
      GITHUB_TOKEN: ${ssm:/github_token}
      AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-instrument
    layers:
      - arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-python-arm64-ver-1-17-0:1