service: otel-demos

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  tracing:
    lambda: true
  architecture: arm64
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'sns:*'
          Resource: '*'
        - Effect: Allow
          Action: 'sqs:*'
          Resource:
            - '*'

custom:
  pythonRequirements:
    slim: true
    dockerizePip: true
    dockerRunCmdExtraArgs: [ '--platform', 'linux/arm64/v8' ]
    dockerImage: public.ecr.aws/sam/build-python3.9:latest-arm64
plugins:
  - serverless-python-requirements
	
package:
  patterns:
    - '!node_modules/**'
    - '!infra/terraform/**'
 
functions:
  get_github_repos:
    module: .
    handler: simple_lambda.get_repos
    timeout: 900
    environment:
      GITHUB_TOKEN: ${ssm:/github_token}
      AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-instrument
      # GITHUB_ORG: upside-services
    layers:
      - arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-python-arm64-ver-1-17-0:1
  
  upside_trifecta_sender:
    module: .
    handler: upside_trifecta_sender.handler
    timeout: 900
    environment:
      GITHUB_TOKEN: ${ssm:/github_token}
      AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-instrument
      # GITHUB_ORG: upside-services
      SNS_RECENT_REPOS_ARN: arn:aws:sns:us-east-1:612245820181:recently_updated_repos
    layers:
      - arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-python-arm64-ver-1-17-0:1
  
  upside_trifecta_consumer:
    module: .
    handler: upside_trifecta_consumer.handler
    timeout: 30
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:612245820181:calculate_action_stats
    environment:
      GITHUB_TOKEN: ${ssm:/github_token}
      AWS_LAMBDA_EXEC_WRAPPER: /opt/otel-instrument
      # GITHUB_ORG: upside-services
    layers:
      - arn:aws:lambda:us-east-1:901920570463:layer:aws-otel-python-arm64-ver-1-17-0:1
